version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
      
    ports:
      - 27081:80
    container_name: wxcloud_elevator
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=elevator
      - role=container
    environment:
      # 使用本地调试 MySQL 时，需要填入如下环境变量，并启动 MySQL 代理服务
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=23Snj2Ug
      - MYSQL_ADDRESS=10.0.224.14:3306
networks:
  default:
    external:
      name: wxcb0
